name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name : dockerhub login
        env :
          DOCKER_USER: ${{dockerhub.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{dockerhub.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag inraep2m2/sbml2rdf:${{  github.ref_name }} 
          docker build . --file Dockerfile --tag inraep2m2/sbml2rdf:latest
      - name : Docker Push
        run: |
          docker push inraep2m2/sbml2rdf:${{  github.ref_name }}
          docker push inraep2m2/sbml2rdf:latest
